### ISSUE TITLE
Runing Problem

### ISSUE THREAD

**Issue by Amirfarhad-Nilizadeh** [yyxhdy/arja#10]
Hi,
During running this tool I get the following warning. 

First I switched the java version of the system to java 1.7.0_80 and I followed the instruction in the read me. Then, I compiled a buggy toy program and its JUnit tests with Java 7. Then, I run the below code and you can see the result. (Also, when I do the whole process with Java8 I will get the same warning).

java -cp lib/*:bin us.msu.cse.repair.Main ArjaE -DsrcJavaDir /home/.../bug_test/src/main \
  -DbinJavaDir /home/.../bug_test/target/main \
  -DbinTestDir /home/.../bug_test/target/test  \
  -Ddependences /home/a~/arja-arja-e/lib
Fault localization starts...
Number of positive tests: 10
Number of negative tests: 10
Fault localization is finished!
AST parsing starts...
AST parsing is finished!
Detection of local variables starts...
Detection of local variables is finished!
Detection of fields starts...
Detection of fields is finished!
Detection of methods starts...
Detection of methods is finished!
Ingredient screener starts...
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1911)
	at us.msu.cse.repair.core.util.Helper.isInSamePackage(Helper.java:392)
	at us.msu.cse.repair.core.parser.ingredient.IngredientUtil.isInIngredientMode(IngredientUtil.java:477)
	at us.msu.cse.repair.core.parser.ingredient.AbstractIngredientScreener.canPreFiltered(AbstractIngredientScreener.java:66)
	at us.msu.cse.repair.core.parser.ingredient.DirectIngredientScreener2.screenIngredients(DirectIngredientScreener2.java:27)
	at us.msu.cse.repair.core.parser.ingredient.AbstractIngredientScreener.screen(AbstractIngredientScreener.java:35)
	at us.msu.cse.repair.core.parser.ingredient.AbstractIngredientScreener.screen(AbstractIngredientScreener.java:30)
	at us.msu.cse.repair.core.AbstractRepairProblem.invokeIngredientScreener(AbstractRepairProblem.java:483)
	at us.msu.cse.repair.ec.problems.ArjaEProblem.invokeModules(ArjaEProblem.java:85)
	at us.msu.cse.repair.core.AbstractRepairProblem.<init>(AbstractRepairProblem.java:271)
	at us.msu.cse.repair.ec.problems.ArjaProblem.<init>(ArjaProblem.java:43)
	at us.msu.cse.repair.ec.problems.PareProblem.<init>(PareProblem.java:39)
	at us.msu.cse.repair.ec.problems.ArjaEProblem.<init>(ArjaEProblem.java:29)
	at us.msu.cse.repair.ArjaEMain.main(ArjaEMain.java:54)
	at us.msu.cse.repair.Main.main(Main.java:8)

**Comment by Amirfarhad-Nilizadeh** [comment]
It seems that one person had this problem and he/she solved the problem by updating dependence's path. But, I am not sure that how I can fix it.

**Comment by Amirfarhad-Nilizadeh** [comment]
Thank you to Yuan that helps me with email. The problem was incorrect package name. It works after I fixed it.
